/**
*ThisprogramperformsthesametaskasCharCountSwitch.javabutwithout
*aswitchstatement.
*/
publicclassCharCountIf{

publicstaticvoidmain(String[]args){
System.out.print("Enterastringofcharacters:");
Strings=System.console().readLine();
intdigitCount=0,punctuationCount=0,letterCount=0;
for(inti=0;i<s.length();++i){
if(s.charAt(i)=='0'
||s.charAt(i)=='1'
||s.charAt(i)=='2'
||s.charAt(i)=='3'
||s.charAt(i)=='4'
||s.charAt(i)=='5'
||s.charAt(i)=='6'
||s.charAt(i)=='7'
||s.charAt(i)=='8'
||s.charAt(i)=='9'){
digitCount++;
}elseif(s.charAt(i)=='!'
||s.charAt(i)=='?'
||s.charAt(i)=='.'){
punctuationCount++;
}else{
letterCount++;
}
//Willthecodeaboveprovideanaccuratecountofletters?
}
System.out.printf("Yourinputcontained%ddigits,%d"
+"punctuaionmarks,and%dletters.%n",
digitCount,punctuationCount,letterCount);
}
}
