/**
*ThisprogramperformsthesametaskasCharCountSwitch.javabutwithout
*aswitchstatement(andiscorrect).
*/
publicclassCharCount{

publicstaticvoidmain(String[]args){
System.out.print("Enterastringofcharacters:");
Strings=System.console().readLine();
intdigitCount=0,punctuationCount=0,letterCount=0;
for(inti=0;i<s.length();++i){
if(Character.isDigit(s.charAt(i))){
digitCount++;
}elseif(Character.isLetter(s.charAt(i))){
letterCount++;
}elseif(Character.getType(s.charAt(i))
==Character.START_PUNCTUATION
||Character.getType(s.charAt(i))
==Character.END_PUNCTUATION
||Character.getType(s.charAt(i))
==Character.CONNECTOR_PUNCTUATION
||Character.getType(s.charAt(i))
==Character.DASH_PUNCTUATION
||Character.getType(s.charAt(i))
==Character.OTHER_PUNCTUATION){
punctuationCount++;
}
//Willthecodeaboveprovideaccuratecounts?
}
System.out.printf("Yourinputcontained%ddigits,%d"
+"punctuaionmarks,and%dletters.%n",
digitCount,punctuationCount,letterCount);
}
}
