publicclassCourseGrade{

publicstaticvoidmain(String[]args){
doublehomeworkAverage=74.2;
doubleexam1=81;
doubleexam2=93;
doubleexam3=95;
doublefinalExam=89;
doubleexamAverage=(exam1+exam2+exam3)/3;
doublecourseAverage=(.2*homeworkAverage)+(.6*examAverage)
+(.2*finalExam);
System.out.println("CourseAverage:"+courseAverage);
chargrade='F';
if(courseAverage>=90)grade='A';
elseif(courseAverage>=80)grade='B';
elseif(courseAverage>=70)grade='C';
elseif(courseAverage>=60)grade='D';
System.out.println("CourseGrade:"+grade);
}
}
