publicclassCourseAverage2{
publicstaticvoidmain(String[]args){
doublehwAvg=74.2;
doubleexamAvg=(81+91+93)/3;
doublefinalExam=89;
doublecourseAvg=(.2*hwAvg)+.6*examAvg+.2*finalExam;
System.out.println("Courseaverage:"+courseAvg);
}
}
