importjava.util.Scanner;

publicclassBlackjackGame{

privatestaticvoidprintHands(BlackjackPlayer...players){
for(BlackjackPlayerplayer:players){
System.out.println(player+"'shand:"+player.getHand());
}
}

publicstaticvoidmain(String[]args){
BlackjackPlayerhouse=newRandomPlayer("House");
Scannerkbd=newScanner(System.in);
System.out.print("What'syourname?");
Stringname=kbd.nextLine();
BlackjackPlayerplayer=newHumanPlayer(name);
Deckdeck=newDeck();
deck.shuffle();
house.dealFaceDown(deck.draw());
player.dealFaceDown(deck.draw());
house.dealFaceUp(deck.draw());
player.dealFaceUp(deck.draw());
booleanshouldKeepPlaying=true;
while(shouldKeepPlaying){
System.out.println("Here'sthetable:");
printHands(house,player);
BlackjackPlayer.MoveplayerMove=player.getMove(house.getHand());
if(playerMove==BlackjackPlayer.Move.HIT){
player.dealFaceUp(deck.draw());
}else{
shouldKeepPlaying=false;
}
BlackjackPlayer.MovehouseMove=house.getMove(player.getHand());
if(houseMove==BlackjackPlayer.Move.HIT){
house.dealFaceUp(deck.draw());
}
}
if(player.getHand().compareTo(house.getHand())>0){
System.out.println("Playerwins.");
}elseif(player.getHand().compareTo(house.getHand())<0){
System.out.println("Housewins.");
}else{
System.out.println("Tie.");
}
}
}
