publicclassGradeBookDriver{

publicstaticvoidmain(String[]args){
GradeBookgradeBook=newGradeBook(3);
gradeBook.add(80);
gradeBook.add(74);
gradeBook.add(92);
gradeBook.modifyScore(1,84);
//Nowscoresare80,84,92
System.out.println("GradeBookscoresare:");
for(intscore:gradeBook.getScores())System.out.println(score);
//Privacyleak:nowwehavealocalreferencetoaprivatevariable:
int[]myReferenceToScores=gradeBook.getScores();
//Wecanuseourlocalreferencetoupdatetheprivateinstancevar:
myReferenceToScores[0]=100;
//Nowscoresare100,84,92:
System.out.println("GradeBookscoresare:");
for(intscore:gradeBook.getScores())System.out.println(score);
}
}
